name: .NET build

on:
  pull_request:
    branches:
      - 'dev'
      - 'main'
  push:
    branches:
      - 'dev'
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore NoSoloAPI

      - name: Build
        run: dotnet build -c Release --no-restore NoSoloAPI
