name: .NET Continuous Integration

on:
  pull_request:
    branches:
      - 'dev'
      - 'main'
  push:
    branches:
      - 'dev'
      - 'main'
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.github/nuget-packages

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ⚙ Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: ♻ NuGet Cache
        uses: actions/cache@v3
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}.nuget.${{ hashFiles('**/*.csproj') }}


      - name: 🔄 Restore Nuget Packages
        run: dotnet restore NoSoloAPI

      - name: 🛠 Build Solution
        run: dotnet build -c Release --no-restore NoSoloAPI
